server:
  port: 8080

spring:
  application:
    name: learn-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.25:8848
        namespace: public
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: learn-auth
          uri: lb://learn-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: learn-menu
          uri: lb://learn-auth
          predicates:
            - Path=/menu/**
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 10000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.learn: debug
    org.springframework.cloud.gateway: debug
